INVALID_COMMAND = "Invalid command."
EXIT_COMMAND = "exit"
CLOSE_COMMAND = "close"
ADD_CONTACT_COMMAND = "add-contact"
ADD_PHONE_COMMAND = "add-phone"
UPDATE_BIRTHDAY_COMMAND = "update-birthday"
UPDATE_ADDRESS_COMMAND = "update-address"
UPDATE_EMAIL_COMMAND = "update-email"
SHOW_CONTACT_COMMAND = "show-contact"
REMOVE_CONTACT_COMMAND = "remove-contact"
ALL_CONTACTS_COMMAND = "all-contacts"

EXIT_COMMANDS = [EXIT_COMMAND, CLOSE_COMMAND]

"""Because we are using rich module, we need to escape square brackets"""
COMMAND_TO_COMMAND_FORMAT_MAP = {
    CLOSE_COMMAND: CLOSE_COMMAND,
    EXIT_COMMAND: EXIT_COMMAND,
    ADD_CONTACT_COMMAND: ADD_CONTACT_COMMAND,
    ADD_PHONE_COMMAND: ADD_PHONE_COMMAND + " \[name] \[phone]",
    UPDATE_BIRTHDAY_COMMAND: UPDATE_BIRTHDAY_COMMAND + " \[name] \[birthday]",
    UPDATE_ADDRESS_COMMAND: UPDATE_ADDRESS_COMMAND + " \[name] \[address]",
    UPDATE_EMAIL_COMMAND: UPDATE_EMAIL_COMMAND + " \[name] \[email]",
    SHOW_CONTACT_COMMAND: SHOW_CONTACT_COMMAND + " \[name]",
    REMOVE_CONTACT_COMMAND: REMOVE_CONTACT_COMMAND + " \[name]",
    ALL_CONTACTS_COMMAND: ALL_CONTACTS_COMMAND
}