INVALID_COMMAND = "Invalid command."
EXIT_COMMAND = "exit"
CLOSE_COMMAND = "close"

EXIT_COMMANDS = [EXIT_COMMAND, CLOSE_COMMAND]

COMMAND_TO_COMMAND_FORMAT_MAP = {
    CLOSE_COMMAND: CLOSE_COMMAND,
    EXIT_COMMAND: EXIT_COMMAND
}